### ISSUE TITLE
请务必支持简体字

### ISSUE THREAD

**Issue by LJZheng-China** [wenyan-lang/wenyan#109]
希望可以同时支持繁体和简体字，以及繁简体的互相转化。

**Comment by nikacan** [comment]
Explain why? Is it not natural to support only the TRADITIONAL characters, since the point of the project is to write in TRADITIONAL chinese?

**Comment by yorkie** [comment]
As the README said, it should be Classic Chinese.

**Comment by melop** [comment]
文言宜以繁體書之。蓋簡體有異字無別之弊，易有歧義。

**Comment by fishfishfishfishfish** [comment]
簡繁體誠無大礙，然以「「」」為引號，余實感不便

**Comment by melop** [comment]
然。吾亦以「」為不便。如語法嚴謹，料引號非必須也。若恐閱讀不便，不妨於變量邊緣留空，蓋文言本無空白，亦無句讀。

**Comment by LingDong-** [comment]
@melop quotes are necessary to distinguish identifiers from keywords. Imagine if you have an identifier, whose substring happens to be a keyword, then ambiguity would be introduced. The only way would be to forbid any identifier to contain any character from keywords, which is obviously a bad idea. Not to mention if more keywords are added to the language, old code will keep breaking.

Most English-based programming languages doesn't have this problem because English naturally have spaces. For Chinese, spaces would look even less appealing than the quotes in my opinion.

Thanks everyone for the discussion!

**Comment by antfu** [comment]
> 希望可以同时支持繁体和简体字，以及繁简体的互相转化。

You can check out the Simplify package `简体秘术` https://github.com/lymslive/wyg-packages/tree/jiantihua by @lymslive
