### ISSUE TITLE
含 0 数字转换出错

### ISSUE THREAD

**Issue by BillZhou233** [wenyan-lang/wenyan#369]
![](https://s2.ax1x.com/2019/12/24/lCV37Q.png)

这个解释器在转换含 0 数字的时候似乎出现了一点小问题。  
根据《高中语文基础知识手册》所述的文言数字表示方法，文言中含 0 数字的表述与普通话中的表述有所不同。上面的图片展示了一个出错的例子。
根据书中所述，古代表述含 0 数字时通常不会使用 "零" 字来说明零位，也就是说一个数末尾的字后面不跟单位时该字就表示个位而非下一位。例如"一百五"在古代是指 __105__ 而非现代的 __150__，"三千三"在古代是指 __3003__ 而非现代的 __3000__。解释器用现代的解释方法解释便会造成问题。

修不修复也不要紧，这只是一个高中 OIer 的小小建议。

BillZhou233 上

**Comment by LingDong-** [comment]
Hi @BillZhou233 ,

The issue is mentioned in #338. Basically, my original implementation is correct, but due to a request in #24, it was changed to the more colloquial interpretation where 二百五=250.

Now that I learned that 205 is the more traditional interpretation, I'll roll back to the previous behavior, when I fix other numeral-related issues.

Thanks for bringing this up!
