### ISSUE TITLE
Core language design: variable declaration as an example

### ISSUE THREAD

**Issue by kaiyuan01** [wenyan-lang/wenyan#467]
Current syntax is very verbose, more like a macro for readability:

wenyan | JavaScript
-- | --
吾有一數。曰三。名之曰「甲」。 | var a = 3;
有數五十。名之曰「大衍」。 | var dayan = 50;
昔之「甲」者。今「大衍」是矣。 | a = dayan;
吾有一言。曰「「噫吁戲」」。名之曰「乙」。 | var b = "alas!";
吾有一爻。曰陰。名之曰「丙」。 | var c = false;
吾有一列。名之曰「丁」。 | var d = [];
吾有三數。曰一。曰三。曰五。名之曰「甲」曰「乙」曰「丙」。 | var a=1,b=3,c=5;

To be more concise, or to be more useful for programming:

數「甲」-> 甲 ("數" is not needed, it defaults to number if not inside a single quote)
「甲」 # means a string as it is inside a single quote, just like in UNix shell

wenyan | JavaScript

-- | --
甲**曰**三。 | var a = 3;
大衍**曰**五十。 | var dayan = 50;
甲**為**大衍」 | a = dayan;
「乙」**曰**「「噫吁戲」」 | var b = "alas!"; # here 「乙」is in a single quote so it's of a string type
**爻**丙**曰**陰。 | var c = false;
**列**丁（**為**空）。 | var d = [];
甲**曰**一。乙**曰**三。丙**曰**五。 | var a=1,b=3,c=5;

Keywords above are in bold.

If this is the way to go, should we write macros for all the above, or refactor the existing code and write another set of macros for existing / more verbose expressions?

**Comment by LingDong-** [comment]
Hi @kaiyuan01 , thanks for bringing this up, but:

This sounds more like a language philosophy issue. I could argue about the numerous merits of the current style like I did before, but more importantly I think wenyan-lang has already grown out of this stage. Take a cat for example, after being a cat for 10 years, the cat suddenly wonders why she wasn't a dog in the first place. Too late to reincarnate isn't it. Better start with a new dog instead of hacking the cat to make it look like a dog.

I think our efforts will have better value if we acknowledge what we currently have, and focus on improving the compiler, the standard libraries, the build/test tools, essential features, and fixing bugs.

Moreover, now with the addition of macros, users can define new syntaxes for themselves and do whatever they like with their own code. Just like in C, you can `#define` all the keywords with emojis or whatever, just don't expect the C committee to incorporate them into its standard :)

Thanks!
