### ISSUE TITLE
「取底除」might not work as expected

### ISSUE THREAD

**Issue by kaiyuan01** [wenyan-lang/wenyan#491]
This simple test did not work as expected:
吾嘗觀「「算經」」之書。方悟「取底除」之義。
吾有二言。曰「「取底除 test: 」」。施「取底除」於四千於四。書之。

The generated function call might have failed:

取底除(4000)(4);

See no output from the online IDE (snippet site has the same result):

![image](https://user-images.githubusercontent.com/5778025/71776381-ed20c300-2f5e-11ea-82d8-61ea5ed6e35b.png)

This might have caused a few functions in Li Fa failed?

**Comment by LingDong-** [comment]
Hi @kaiyuan01 ,

Sorry 取底除 is a new addition to the standard library that is not available on the online IDE yet. You can uncheck the box "Hide Imported Code" and see what is actually being imported.

I just rebuilt the site and now this function should work. However, there are still a couple of problems with your code:

- Since you only specified one string literal after 吾有二言, it should be 吾有一言 instead.
- Since 取底除 is an object, so you can't just print it like that. You'll have to print the 商 and 餘 fields separately, at least for now, until we implement a new printing mechanism.
- Avoid using keywords in English when Chinese counterparts are readily available.

Thanks!

**Comment by kaiyuan01** [comment]
![image](https://user-images.githubusercontent.com/5778025/71786526-585bab00-2fda-11ea-8cbd-d40c3c0bd428.png)
 Still nothing came up.

**Comment by LingDong-** [comment]
@kaiyuan01 Your browser is caching the old page.
Here is a tutorial on how to clear cache for popular browsers: https://kb.iu.edu/d/ahic .
Thanks
