### ISSUE TITLE
help: how to build wenyan from source

### ISSUE THREAD

**Issue by lymslive** [wenyan-lang/wenyan#493]
Hello, 
I'm not very familiar with js. I know install `wenyan` followed by README `npm install -g @wenyanlang/cli`. Then I can play with wenyan-lang.

But I wonder how to build from source after clone down this repository? Then I may taste the newest functionality, or bugs.

So what command used to manually build `wenyan` cli, where will it output default, and what modules it dependents? Is there any instruction? thanks.

**Comment by LingDong-** [comment]
Hi! I think you can simply run `src/cli.js` directly, like so

```
node src/cli.js
```

@antfu , please feel free to add or correct me if I'm wrong.

Welcome to taste the newest bugs :)

**Comment by kaiyuan01** [comment]
You can try:

npm i
npm run build
npm t

**Comment by lymslive** [comment]
@kaiyuan01
Thanks, I've tried out.

`npm install` seams install the depented modules? I found in current pwd created a dir named `node_modules` filled with lots of modules. May I mv it to system path such as `/usr/local/lib/node_modules` ?

`npm run build` will build in a dir name `dist` under pwd, I can find cli in it.

**Comment by kaiyuan01** [comment]
@lymslive You are right, it installs all dependencies for the project. I could be wrong, but I think better  keep everything under project root directory.

**Comment by LingDong-** [comment]
@lymslive You can use `npm install -g` to install globally, but I think the philosophy of npm is to keep dependencies within the project folder (unless it is intended to use as a cli tool). This tend to reduce version conflicts etc.

<sub>My personal suggestion is to not even look into the `node_modules` folder. Chances are there will be a billion little folders in there because of dependencies of dependencies of dependencies. Just use `package.json` and trust npm to manage everything else for you :D </sub>

**Comment by lymslive** [comment]
OK, after I move modules to system path, I found fail to `npm run build` when pull newer version.
So I have to move them back :)

**Comment by antfu** [comment]
Hope your problem gets resolved. Closing for now. Feel free to reopen if you get any questions.
