### ISSUE TITLE
希望为撰写文档提供帮助，应该如何加入？

### ISSUE THREAD

**Issue by ZGarry** [wenyan-lang/wenyan#508]
于闲暇得观此project，心喜之。斗胆欲作出一二贡献，撰写Code不敢妄为，私拟为文档撰写提供些许帮助。

但在下有点垃圾，希望能得到引导。

个人情况：程序员。了解JS，Git，团队协作。有闲暇时间与对古文的热爱。

**Comment by ZGarry** [comment]
另外是使用后的一些建议：
1.在醒目位置添加 interactive模式的退出，下面这些方法都无法退出
![image](https://user-images.githubusercontent.com/43488431/71958925-73bdf480-322c-11ea-99a0-cd02cdc1ecfe.png)

2.似乎不支持简体中文，能否加以支持

**Comment by ZGarry** [comment]
如果此issue提交得并不合适，请关闭

**Comment by lymslive** [comment]
interactive 模式似乎还应该有 “帮助” 命令。

另外，该语言内核我支持坚持用繁体中文，那比较有底蕴。但要能支持用户扩展简体规范，我也有此打算利用现在的宏机制试一下。

**Comment by cuixiping** [comment]
在循環中，使用 `乃止` (break;)
在函數中，使用 `乃得` (return;)

**Comment by LingDong-** [comment]
Hi @ZGarry , good suggestions!

> 在醒目位置添加 interactive模式的退出，下面这些方法都无法退出

`Control-C` or `Control-D` exits the interactive REPL. 

But notice that for e.g. in python REPL quit() works because it is a python function whose functionality is to exit execution, regardless of whether in interactive mode or not. Therefore the real question is, whether wenyan should support immediately exiting the execution of a program, like `quit()/exit()` in python or `exit(0)` in C or `process.exit()` in JavaScript. Discussions are welcome.

> interactive 模式似乎还应该有 “帮助” 命令。

If you mean help on the CLI itself, you can do `$ wenyan -h` or even just `$ wenyan` to print the usage. If you mean something like C's `man xx` or python's `help('xx')`, then no we don't have that currently. We'll need to write the documentation for everything to make this possible, so it might take a while.

> 似乎不支持简体中文，能否加以支持

Like @Iymslive mentioned, it is unlikely that we'll ever support Simplified Chinese. This is discussed multiple times, and some of the reasoning can be read here: https://github.com/LingDong-/wenyan-lang/pull/442#issuecomment-569865551. However, like @lymslive mentioned, you can use macros to add that support for yourself if you really need it.

Thanks for bringing these up!
