### ISSUE TITLE
Docs site

### ISSUE THREAD

**Issue by antfu** [wenyan-lang/wenyan#516]
First, congrats for the new IDE 🎉 It looks awesome!

I am working on a doc website for wenyan in order to provide better documentation and tutorials for users to reference.

You can check it out by https://wenyan-docs.netlify.com/ (very early stage, just simply vendored the docs from this project, and the source is in a private repo (yet))

## Things I may need help
- Tell me what you think of this idea! If you like it, I'll move it to `wenyan-lang` org when it's ready
- **SVG version of the Logo** - the logo provided in the repo is a little too low-res. May need a better logo for website/tools/avatar/3rd-party references. (The current logo in the docs is a mimicry I made for wenyan-lang-vscode, and I can not found the font exact matched to the given one)
- Maybe we need some brand colors as well.

## Things to be done for the docs
- Syntax highlight for wenyan block
- A REPL component for interactive demos
- Font & style adjust
- Fulfill the docs
- Tutorials

**Comment by LingDong-** [comment]
Wow! Great job, doc site looks nice!

Some thoughts:

- I've been thinking about adding a doc site too. But I have a slightly different idea regarding details: maybe it could be of an online-book-like form. It will be more an official introduction/handbook to the language, focusing more on the syntax/programming side. We can keep the install instructions & links on the Github Repo (or Wiki). (And later we might even translate the book into classical Chinese or print physical versions etc. but that's for the future). 

- Perhaps we can call it 文言正義 after 五經正義 etc. or some variation or along the lines of 文心雕龍. I plan on start working on the book once I get current things off my table, and implement the last few syntax features. 

- One source of inspiration I can think of from the top of my head is [Book of Shaders](https://thebookofshaders.com/). Ours will be very different, but I think they have many elements I enjoy (explanation, interactive example, chapters, etc. ). Let me know what you think!

- And I can work on some page layout/design to make the site look unique and reminiscent of classical motifs. Currently it looks nice but generic-template-ish (I know it's a quick test, just listing TODO's here :P)

- The brand colors can be the ones used on the front page and the renderings (# E53, # 248, # 872). They come from 四色套印 colors used in traditional printed books, e.g. https://www.shuge.org/ebook/hu-shan-sheng-gai/ . I picked the colors by eyeballing, perhaps they can use some more tweaking.

- The logo is something I put together quickly. The font is Menlo because macOS happen to ship with it. Again, I'll experiment more to see if there's something I can tweak. Here is a svg (it's zipped because Github doesn't support svg upload for some reason):

[wy-logo.svg.zip](https://github.com/LingDong-/wenyan-lang/files/4046850/wy-logo.svg.zip)

Thanks for reading :D

**Comment by antfu** [comment]
> maybe it could be of an online-book-like form. It will be more an official introduction/handbook to the language, focusing more on the syntax/programming side. 

The book idea sounds great! (and looking forward to the classical Chinese version 😄). It's definitely great to have a formal documents for a language.

> We can keep the install instructions & links on the Github Repo (or Wiki).

How about we keep both the `book` and the `docs` site? The main reason I am trying to make this doc is to make newcomers get started more quickly. I think the current "linear" style of the readme is not intuitive to know where to start. Jumping documents in Github may be easier to got lost as well.

The doc is built by [vuepress](https://github.com/vuejs/vuepress). There are some benefits I can think about.
- Search for documents
- Multi-languages support, it will be a dropdown menu on the rightmost nav bar to select the language. And it well be more manageable.
- Easier to navigate.
- Custom syntax highlight for wenyan.
- Interactive examples - just as you did for the `site`
- Can be separated from the main repo
- Easier for people to contribute.

I think we can keep the doc site for `Beginner Guides` `Tutorials` `Installations` and `Tools index` (or maybe `awesome-wenyan` as well). While the `book` focusing on the formal language/syntax details.

> Book of Shaders

Looks awesome! Thanks for sharing!

> I think they have many elements I enjoy (explanation, interactive example, chapters, etc. 

We can have them too! I think we should rewrite the docs for guides for the better reading.

> And I can work on some page layout/design to make the site look unique and reminiscent of classical motifs.

Of course. Will definitely do that!

----

Let me know what you think about it. Thanks!

**Comment by LingDong-** [comment]
Sounds great!

> The main reason I am trying to make this doc is to make newcomers get started more quickly. I think the current "linear" style of the readme is not intuitive to know where to start. Jumping documents in Github may be easier to got lost as well.

Totally make sense. My main concern is that, since I suppose we still want to have something in the main README to attract Github users (I think people are unlikely to get interested if the README is just 3 lines and 2 links), we'll need to make duplicate work to maintain both places. For example, the Traditional/Simplified Chinese README's are probably way outdated because it appears that we don't have enough manpower to maintain all three.

I wonder if we can generate the doc site from the README. Technically this is not difficult (the spec page is generated this way), but I'm not familiar with vuepress (it seems really nice) so I hope it's also possible with vuepress.

**Comment by antfu** [comment]
> we'll need to make duplicate work to maintain both places. 
> I wonder if we can generate the doc site from the README.

Vuepress builds the site from markdown files. And don't worry, automation is where my passion is 💪🤣. Since it will CI/CD by netlify we can easily write scripts to generate docs/lists from different sources. (separated project docs like wyg can be unified as well!)

> For example, the Traditional/Simplified Chinese README's are probably way outdated because it appears that we don't have enough manpower to maintain all three.

Auto-translating between Traditional/Simplified Chinese is also possible. We can also have a lookup dict for replacing terms used in different areas (e.g. `面向对象` vs `物件導向`, OOP). *And maybe there already exist some ditct available to use.*

> My main concern is that, since I suppose we still want to have something in the main README to attract Github users (I think people are unlikely to get interested if the README is just 3 lines and 2 links), 

We should surely put something in the README but I think we can keep this README minimal (with quick examples and screenshots). Parts like tools or the apis docs can be moved to the docs repo.

**Comment by antfu** [comment]
@LingDong- In case of misleading, I think we should keep the docs repo private before it's ready. I have sent you an invitation to access the repo so you can have a better view of what's going on :)

https://github.com/antfu/wenyan-docs

**Comment by LingDong-** [comment]
@antfu Great, thanks! I was going to say we could put docs as private repo under the organization, but apparently Github freeloaders like me are not privileged enough to do so :P

Also, shall we rename `wenyan-lang/syntax` to `wenyan-lang/highlight`? "Syntax" might be misleading because it could be referring to the wenyan syntax itself, i.e. spec.

**Comment by antfu** [comment]
> I was going to say we could put docs as private repo under the organization, but apparently Github freeloaders like me are not privileged enough to do so :P

Yes exactly 😂

> Also, shall we rename wenyan-lang/syntax to wenyan-lang/highlight? "Syntax" might be misleading because it could be referring to the wenyan syntax itself, i.e. spec.

No problem

**Comment by antfu** [comment]
Close due to the new [wiki docs](https://github.com/wenyan-lang/wenyan/wiki)
