### ISSUE TITLE
IDE should allow compile code snippet which has undefined variables

### ISSUE THREAD

**Issue by cuixiping** [wenyan-lang/wenyan#549]
## Describe your issue/suggestions

Sometimes, we just want to take a look at the compile result, not really run it.

```
加「甲」以「乙」
```

When I click [**compile**] button, I expect to see

```
var _ans1 = 甲 + 乙;
```

Currently, the IDE will refuse to compile the code snippet since the typechecker will raise an error.
`TypeError: Cannot read property 'type' of undefined`

It will be better to raise the error when click the [**run**], or [**check**] button, but not [**compile**] button.

How do you think about it?

**Comment by LingDong-** [comment]
Hi @cuixiping , You can hit `run` to compile it without typecheck.

**Comment by antfu** [comment]
Emm, will it better to introduce a checkbox for `strict` or `typecheck`? I do like the type prints on the output when hinting compile but maybe it's not very intuitive for users? @LingDong-

**Comment by LingDong-** [comment]
Make sense. If we add the checkbox, it probably needs to be global to both `run` and `compile`, otherwise it might be confusing. One possible behavior is that, when hitting run and the checkbox is checked, typecheck is done, but only prints type error/info to the `out` div when there's a problem, otherwise the output of the program is printed to `out` div.
@cuixiping @antfu What do you think?

**Comment by antfu** [comment]
Sounds great to me!

**Comment by cuixiping** [comment]
The compile should always work if there is no syntax error.
The best way to show typecheck errors is `wenyan-lint` just like eslint, show warning or error message in codemirror. Before there is a  `wenyan-lint` , a checkbox will be good.
