### ISSUE TITLE
How to disable Chinese numeral output in the cli?

### ISSUE THREAD

**Issue by statementreply** [wenyan-lang/wenyan#565]
None of the following work
- `--outputHanzi=false`
- `--outputHanzi false`
- `--no-outputHanzi`

**Comment by LingDong-** [comment]
Thanks for spotting the issue! I think commander.js does not support unsetting a defaultly true flag to false:

https://github.com/tj/commander.js/issues/344
https://github.com/tj/commander.js/issues/928

I think we should change the option to `--no-outputHanzi` and default it to false.

Also I discovered some issues with repl mode. Will fix today.

**Comment by LingDong-** [comment]
Fixed! 2d90cb7fca06b1ba1e09d4c139446c8c74a14f01

- `--no-outputHanzi` should work correctly now (`ts-node src/cli.js --no-outputHanzi`), except for interactive REPL mode, where it never outputs Hanzi. Will see what I can do.

**Comment by antfu** [comment]
@LingDong-  Oh wait, the duplicated commits get back 🤣

**Comment by antfu** [comment]
I have reverted them. Maybe it's better for you to delete the repo and clone again. XD

**Comment by LingDong-** [comment]
@antfu Oh crap, thanks for fixing it! I re-cloned. Actually I have 9 messed-up versions of this repo on my disk due to similar situations. Got to love how easy it is to work with git XD

--- 

I've now added some improvements to the REPL.

e05bf9a4743d90bc3e9ff8fbc4f77e43cad75327

- REPL now has ability to output Hanzi, and respects `--no-outputHanzi`
- Use up and down arrow keys to load previous input, like shell/any standard REPL!

**Comment by antfu** [comment]
I am using [GitKraken](https://www.gitkraken.com/) FYI. It's a handy tool for manage complex projects 😉
