### ISSUE TITLE
Compiler

### ISSUE THREAD

**Issue by XingZiLong** [wenyan-lang/wenyan#594]
My browser (I am using my iPad Safari) have been out of order when executing the code below:
![B309B5B9-E05B-4F85-A093-BDE85C5D28EA](https://user-images.githubusercontent.com/41220208/76481611-df9b2400-644c-11ea-8e9d-c1cde73c1e0a.png)

**Comment by XingZiLong** [comment]
My compiler didn’t report any exceptions but I just can’t execute it.

**Comment by LingDong-** [comment]
Hi, I think you have an infinite loop.

You can try clicking the "compile" button to see the compiled JS:
![image](https://user-images.githubusercontent.com/7929704/76483398-50aaef00-63ed-11ea-99ea-3b089ceee945.png)

Not sure what you're calculating, but running the compiled JS offline, it seems that 甲 never equaled to 乙.

Tip: if possible, post the plain text instead of an image, it'll be much easier for maintainers to try it out :) 

Thanks!

**Comment by XingZiLong** [comment]
Thanks for your help, but I come across another problem. I can’t select any text in my IDE. Maybe I am using Safari?
I’ll check my code again!
(I am going to write a program to factorize a number.)

**Comment by LingDong-** [comment]
> I can’t select any text in my IDE

Maybe try refreshing the page?

I don't have access to an iPad right now but text selection seems to work on my iPhone Safari:

<img src="https://user-images.githubusercontent.com/7929704/76484376-037c4c80-63f0-11ea-8ef0-c1ad2fe38dd7.png" height="200">

The IDE is using codemirror for all its code cells. Wondering if you could select text in other codemirror widgets, e.g. on their official site:

https://codemirror.net

**Comment by XingZiLong** [comment]
Okay, thanks for you help.
