### ISSUE TITLE
[Feature Request] Random

### ISSUE THREAD

**Issue by ExerciseBook** [wenyan-lang/wenyan#87]
In https://github.com/LingDong-/wenyan-lang/blob/master/examples/divination.wy , I defined a random number generator function by JavaScript.
Maybe we can change it into an individual keyword.

**Comment by LingDong-** [comment]
Yup I'm definitely going to fix that. As explained in [this](https://github.com/LingDong-/wenyan-lang/issues/2) and [this](https://github.com/LingDong-/wenyan-lang/issues/55) issue, Randomness among other math functions most likely be implemented as standard library function calls instead of making its way into the syntax.
Btw, thanks again for your example, I myself couldn't have implemented it better ;)

**Comment by ExerciseBook** [comment]
OK, I see. Thx.

**Comment by antfu** [comment]
It's part of stdlib now: https://github.com/wenyan-lang/wenyan/blob/master/lib/%E6%98%93%E7%B6%93.wy 🎉

**Comment by hiking93** [comment]
Is there any way to set current timestamp as the random seed? Both [divination.wy](https://github.com/wenyan-lang/wenyan/blob/v0.4.0/examples/divination.wy#L4) and [
tree2.wy](https://github.com/wenyan-lang/wenyan/blob/v0.4.0/examples/tree2.wy#L5) set a constant number as the seed, so they generate the exact same results every time we run.

In [西曆法.wy](https://github.com/wenyan-lang/wenyan/blob/v0.4.0/lib/js/%E8%A5%BF%E6%9B%86%E6%B3%95.wy) we currently have no functions that return current time in milli-seconds. May need to create one?
